"""Session authentication for the core's HTTP surface.

This is step 5 of the `ARCHITECTURE.md § 3.1` handshake, and the whole of the
"another process talking to the core" row of the `§ 8.6` threat model. Three
independent things have to hold before a request reaches a route:

1. **No `Origin` header.** MAIN is a Node client and never sends one. A browser
   always does, so an `Origin` means a web page found the port — reject.
2. **A matching bearer token.** 256 bits, generated by MAIN, handed over a pipe
   on stdin, compared here in constant time.
3. **The peer is the supervisor itself.** The process on the other end of the
   connection, resolved from the OS connection table, must be MAIN — the exact
   process, not a relative of it.

`§ 3.1` step 5 originally said "the supervising PID's child chain", and P0-16 is
the task that narrowed it, because the core is itself a descendant of MAIN and so
therefore is **every job the core spawns**. A PowerShell script or a Playwright
browser the agent starts would have passed that rule, which would have let a
compromised job drive the agent through the agent's own API — the one caller
that is trusted to move the mouse. Nothing needs the wider rule: MAIN is the only
client, `core-gateway.ts` and `core-stream.ts` both open their sockets in MAIN's
own process, and MAIN passes its own `process.pid` as `--supervisor-pid`.

The supervisor is identified by **PID *and* creation time**, snapshotted while it
is still known to be the process that spawned us, for the reason `parent_watch`
gives: Windows reuses PIDs, so a PID on its own names a slot, not a program.

Any one of the three failing gives the same bare `401`: a prober must not be able
to learn *which* check it tripped. The real reason is logged, never returned.
"""

from __future__ import annotations

import hmac
import logging
import time
from collections.abc import Awaitable, Callable, MutableMapping
from dataclasses import dataclass, field
from typing import Any, Final, Literal

import psutil

from aegis_core.parent_watch import GONE, UNIDENTIFIED, Identity, process_identity

log = logging.getLogger(__name__)

Scope = MutableMapping[str, Any]
Receive = Callable[[], Awaitable[MutableMapping[str, Any]]]
Send = Callable[[MutableMapping[str, Any]], Awaitable[None]]
ASGIApp = Callable[[Scope, Receive, Send], Awaitable[None]]

#: Why a request was refused. Logged, never sent to the caller.
RejectReason = Literal["origin_present", "bad_token", "untrusted_peer", "unknown_peer"]

#: `ARCHITECTURE.md § 3.1` step 1. MAIN generates this many random bytes.
TOKEN_BYTES: Final = 32

_BEARER: Final = "bearer "

#: Longer than a hex-encoded 256-bit token and short enough to bound the compare.
_MAX_AUTHORIZATION_CHARS: Final = 1024

#: A resolved peer stays trusted this long. Connections are keep-alive, so this
#: turns one OS connection-table scan per connection into one per five seconds,
#: while staying far shorter than the TIME_WAIT that keeps a local port from
#: being handed to a different process.
_PEER_CACHE_TTL_SECONDS: Final = 5.0

#: Bounded on purpose — `REVIEW.md § 2` forbids an unbounded in-memory buffer.
_PEER_CACHE_MAX_ENTRIES: Final = 256


class PeerLookupError(Exception):
    """The OS would not tell us which process is on the other end."""


def resolve_peer_pid(local_port: int, peer_port: int) -> int | None:
    """Return the PID owning the socket connected to `local_port` from `peer_port`.

    Reads the peer's own row in the connection table — the one whose *local* end
    is the peer's port — so our own mirrored row can never be mistaken for it.
    Returns `None` if no such row exists (the peer closed, or the OS hid it).
    """
    try:
        connections = psutil.net_connections(kind="tcp")
    except (psutil.AccessDenied, psutil.Error) as error:  # pragma: no cover - OS-dependent
        raise PeerLookupError(str(error)) from error

    for connection in connections:
        laddr = connection.laddr
        raddr = connection.raddr
        if not laddr or not raddr:
            continue
        if laddr.port == peer_port and raddr.port == local_port:
            return connection.pid
    return None


def identities_match(baseline: Identity, current: Identity) -> bool:
    """Whether `current` still describes the process `baseline` was taken from.

    A process that is `GONE` is never a match. A process the OS will not describe
    is treated as a match, the same way `parent_watch` treats it as alive: the
    pair cannot be compared, and refusing on `AccessDenied` would make the core
    unreachable to its own MAIN the moment permissions tightened. The PID still
    has to be right and the caller still has to hold the token, so this widens
    the rule only from "MAIN" to "whatever holds MAIN's PID", never to a chain.
    """
    if current is GONE:
        return False
    if current is UNIDENTIFIED or baseline is UNIDENTIFIED:
        return True
    return current == baseline


#: Injected so the middleware can be tested without real sockets.
PeerResolver = Callable[[int, int], int | None]

#: Injected so the supervisor's identity can be faked in tests.
ProcessIdentifier = Callable[[int], Identity]


@dataclass
class _PeerCache:
    """Short-lived, bounded memo of "this peer port belongs to a trusted process"."""

    entries: dict[tuple[str, int], tuple[float, bool]] = field(default_factory=dict)

    def get(self, key: tuple[str, int], now: float) -> bool | None:
        entry = self.entries.get(key)
        if entry is None:
            return None
        expires_at, trusted = entry
        if now >= expires_at:
            del self.entries[key]
            return None
        return trusted

    def put(self, key: tuple[str, int], trusted: bool, now: float) -> None:
        if len(self.entries) >= _PEER_CACHE_MAX_ENTRIES:
            for stale_key, (expires_at, _) in list(self.entries.items()):
                if now >= expires_at:
                    del self.entries[stale_key]
            if len(self.entries) >= _PEER_CACHE_MAX_ENTRIES:
                self.entries.clear()
        self.entries[key] = (now + _PEER_CACHE_TTL_SECONDS, trusted)


@dataclass
class SessionAuth:
    """The credentials and the peer rule this core instance was started with."""

    #: The token MAIN sent over the stdin pipe. Never logged, never in a response.
    token: str
    #: MAIN's PID. The connecting process must be *this process*, nothing below it.
    supervisor_pid: int
    #: The port we are actually bound to, filled in after the socket exists.
    local_port: int = 0
    resolve_peer: PeerResolver = resolve_peer_pid
    identify: ProcessIdentifier = process_identity
    _cache: _PeerCache = field(default_factory=_PeerCache, repr=False)
    #: MAIN's creation time, taken now — while the PID is still known to be the
    #: process that started us — so a later reuse of it cannot pass for MAIN.
    _supervisor_identity: Identity = field(init=False, repr=False, default=None)

    def __post_init__(self) -> None:
        self._supervisor_identity = self.identify(self.supervisor_pid)

    def token_matches(self, header: str | None) -> bool:
        if header is None or len(header) > _MAX_AUTHORIZATION_CHARS:
            return False
        if not header.lower().startswith(_BEARER):
            return False
        return hmac.compare_digest(header[len(_BEARER) :].strip(), self.token)

    def is_the_supervisor(self, pid: int) -> bool:
        """Whether `pid` is the very process that started this core.

        Not "is descended from" — see the module docstring. The core's own
        children are descendants of MAIN too, and they must never pass.
        """
        if pid != self.supervisor_pid:
            return False
        return identities_match(self._supervisor_identity, self.identify(pid))

    def peer_is_trusted(self, peer: tuple[str, int] | None) -> bool:
        """Whether the process on the other end of the connection is ours."""
        if peer is None:
            return False
        now = time.monotonic()
        cached = self._cache.get(peer, now)
        if cached is not None:
            return cached
        try:
            pid = self.resolve_peer(self.local_port, peer[1])
        except PeerLookupError:
            # Deliberately not cached: a transient OS refusal must not pin a
            # denial onto a peer that is in fact ours.
            return False
        if pid is None:
            return False
        trusted = self.is_the_supervisor(pid)
        if not trusted:
            # PIDs are not secrets, and "which process was that?" is the only
            # question worth asking when a legitimate client starts failing.
            log.warning(
                "core.peer_untrusted",
                extra={"peer_pid": pid, "supervisor_pid": self.supervisor_pid},
            )
        self._cache.put(peer, trusted, now)
        return trusted

    def reject_reason(
        self, headers: dict[str, str], peer: tuple[str, int] | None
    ) -> RejectReason | None:
        """`None` means the request may proceed. Order is cheapest check first."""
        if "origin" in headers:
            return "origin_present"
        if not self.token_matches(headers.get("authorization")):
            return "bad_token"
        if not self.peer_is_trusted(peer):
            return "untrusted_peer"
        return None


def _headers_of(scope: Scope) -> dict[str, str]:
    raw: list[tuple[bytes, bytes]] = scope.get("headers", [])
    return {key.decode("latin-1").lower(): value.decode("latin-1") for key, value in raw}


def _peer_of(scope: Scope) -> tuple[str, int] | None:
    client = scope.get("client")
    if client is None:
        return None
    host, port = client
    return (str(host), int(port))


class SessionAuthMiddleware:
    """Rejects everything that is not MAIN, before any route runs."""

    def __init__(self, app: ASGIApp, auth: SessionAuth) -> None:
        self.app = app
        self.auth = auth

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] not in ("http", "websocket"):
            await self.app(scope, receive, send)
            return

        reason = self.auth.reject_reason(_headers_of(scope), _peer_of(scope))
        if reason is None:
            await self.app(scope, receive, send)
            return

        log.warning(
            "core.request_rejected",
            extra={"reason": reason, "path": scope.get("path", ""), "scheme": scope["type"]},
        )
        if scope["type"] == "websocket":
            await send({"type": "websocket.close", "code": 1008})
            return
        await send(
            {
                "type": "http.response.start",
                "status": 401,
                "headers": [
                    (b"content-type", b"application/json"),
                    (b"content-length", b"26"),
                ],
            }
        )
        await send({"type": "http.response.body", "body": b'{"detail":"unauthorized"}\n'})
